export const Errors = {
  EMAIL_INCORRECT: 'email_incorrect',
  FOOD_STORE_ALREADY_EXISTS: 'food_store_already_exists',
  FOOD_STORE_NOT_FOUND: 'food_store_not_found',
  FOOD_STORE_TABLE_ALREADY_EXISTS: 'food_store-table_already_exists',
  FOOD_STORE_TABLE_NOT_FOUND: 'food_store_table_not_found',
  GENERIC_ERROR: 'generic_error',
  MENU_ALREADY_EXISTS: 'menu_already_exists',
  MENU_ITEM_ALREADY_EXISTS: 'menu_item_already_exists',
  MENU_ITEM_NOT_FOUND: 'menu_item_not_found',
  MENU_NOT_FOUND: 'menu_not_found',
  NOT_AUTHORIZED: 'not_authorized',
  USER_ALREADY_EXISTS: 'user_already_exists',
  USER_NOT_FOUND: 'user_not_found',
};
